### PR TITLE
Style framework, Project #: 8 Request for Code review

### PR DESCRIPTION
**Pull request by wickathou**
Features:
+ A framework built on LESS
+ A custom documentation page
+ Responsive and customizable styling

### CODE REVIEW

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi @wickathou, 

I understand this is supposed to be a collaborative project. Could you please enlighten us on the reason you did it solo?

You have really done great jobs with this project. But please let's address the below issues:

- [x] It seems your framework doesn't have classes to define columns sized from 1/12th of the row to 100% of the row _(Point number 4 on Odin Project)_
- [x] Files not related to the project should not be committed and added to .gitignore
_What is the function of [this file](https://github.com/wickathou/documentation-html-template/tree/966157f94fff23846f96df1d4332115f533bf9f5)?_
- [x] There are failing checks (stickler); please fix them.

**Kindly request another code review request after fixing those issues**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by wickathou** [comment]
I don't have a coding partner.

+ Added all widths of the columns for grids
- The guide repo, is the documentation of the framework
- The checks make no sense, Stickler doesn't seem designed to handle LESS so it highlights non-existent issues

**Comment by ebukaume** [comment]
# Changes Required! :stop_sign: 

Hi @wickathou, 

Please refer to [this doc](https://stickler-ci.com/docs#stylelint); it says stickler can lint LESS too. Kindly make necessary changes and clear the errors, please.

**The errors are very real. You can see here that you actually declared `duplicate padding`**.
https://github.com/wickathou/presnsr-css/blob/1c48317638a425e778a9174132963f9d4829c0fb/presnsr.less#L299-L308

About `no-descending-specificity`, you should refer to [this article](https://stylelint.io/user-guide/rules/no-descending-specificity)

Also, the second point about files not related to the project has not been addressed.

Finally, I have gone through the guide on the README file, and I couldn't find classes to define columns sized from 1/12th of the row to 100% of the row as mentioned in _Point number 4 on Odin Project_


**Kindly request another code review request after FIXING those issues** If you need further clarifications, you can comment here or reach me on slack. 

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by wickathou** [comment]
- Tthe Guide folder is the **Documentation**. While I don't push to master, when you check it, you see a branch that's not attached to this repo. Here's the branch that you should see
https://github.com/wickathou/documentation-html-template/tree/presnsr-guide

- All other issues fixed

**Comment by ebukaume** [comment]
## Approved :champagne: 

Hi @wickathou :wave: 

**You can go ahead and merge this PR.** 

Good luck with your next projects.


Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Pull request merged**
